name: Workflow for checking http status codes

on:
  push:
    branches: [ main ]
    tags: [ '*.*.*' ]
    workflow_dispatch:

jobs:
  build:
    name: HTTP Status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check HTTP status
        uses: ./
        with:
          url: ${{ secrets.URL }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          code: 200
          timeout: 60
          interval: 10